project:
  create: true
  name: gepaplexx

applications:
################## RESOURCE LOCKER OPERATOR ###################
  resourceLocker:
    name: resource-locker-operator
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gp-infrastructure
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-chart-development/"
      chart: gp-resource-locker
      targetRevision: "*"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

################## SEALED SECRETS OPERATOR ####################
  sealedSecretsOperator:
    name: sealed-secrets-operator
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gp-infrastructure
      create: false
    source:
      chart: sealed-secrets
      repoURL: https://bitnami-labs.github.io/sealed-secrets
      targetRevision: 2.*
      helm:
        parameters:
          - name: containerSecurityContext.enabled
            value: 'false'
          - name: podSecurityContext.enabled
            value: 'false'
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

###################### IDENTITY PROVIDER ######################
  identityProvider:
    name: identity-provider
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gp-infrastructure
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-chart-development/"
      chart: gp-identity-provider
      targetRevision: "*"
      helm:
        parameters:
          - name: "google.clientSecret"
            value: "AgBXKVrQkK+xcoeoT/6R6oZiJ50r/GIVSWs1FQq18JYOOy3PmsK6mr7AiB2Kvcz+CH9yHRZ/5EhwdUaz6XhqbxqMqAs2TeV4TFwvj5VveZ9CIKPN4Anx1fX29rCtGSnTJcHH88pUm75yMrde2YMAFewpyhifo0LEQgHl9uziicHGLYePUxnukRYXmFbBvjwXRXf+e8CMNKZnefJGR3vZuKkR8E6bqMcxGOIiMEc/pLmMlG2H+obK8g3uOOWBxZJUPy1pdn395iUJWpDx8jWtfelfm8nkp08E/XlNGcukIGmkVefNsFrIz/HbWwouLNw10pFW3FnDnZdQjnDG3CC34v+zOl0CQ7kV9rqTEgibcTS8ZGI5Lx7avyS5px7Mg50OsZDqlkYX6yKLgtrU3pUTNQE2xfNCNh2FMjVsuXBBEGmpP+5OcLZuhObsLAPDZ+FT1i/sjwR6ntYYP/7HlTNLNb1etyIa+VpvB4QLM0GslCHR/T6hBEmHpRq6oaWi7Pc2GVl9GXcwZgH1x/bseT9kBwgtHHdSXsrY0pz4wZfixvYkplv3v0LiWGpCU1oh+zcYQcnQ5/LUydg5k9egDwdrxBYdKYR+YYZ0mWWipKZwXaYoPDC0ryyrlXjRLa1Iz67OUJ++DRTViNk9FlAGT53EB2uGGTagWq8RiS6YN2uQSX1WptCV4FGgc0scjgKo17E2KwVIol8jxmK5sXk+YJDF0hsTe7GKwo0N7do="
          - name: "google.clientId"
            value: "AgC1bHDrbAn90M+N6R5iaQ8LlAJ0hWbVtWddTVFd6i+cjCqFUX4CZIBPYB5tQXZalbgzW3h1KQvzs0kprJY50R1S1h6FcGGXuj1Oioe4fvv/0mX2q3ZyxOpqJelJWPc1x5XvBuabGiZyP/sPw57sO2Tb9syxRgZLbRiv97plhgvncRFw39KDF78iMXbAIGQkwSAje3Zcesh/cswnPm6pT90CAE2BdBvJ/1Zme6DcYvpqamzpoO0px69WCsKPKghWGwdNa093j4TmRs/a1wO7fECAgU21CkVChAS6Om77txzdp/Doer1xgp+ixm5MXHTexYtnpJ5clhDe1wz9pbI486sXvQDtim7SRMVSVRO6fXxZr15/ZTma48eWo9la278QxUwgXJXTreOw4S3Ytwh5fggsO1mrAK4dPtFRihJBg4/80duXcByy550PNd+GnkoyOJv3byxi0uv945DX0BOorJNGQSwWzEwgG/8JOg2B1x2kLt+j/a6wJBepXoI69caz4NXqsyZRnvm5joRaWG3VoQpMeEXoamlC+lZQ5nmxTyjyfYAbYUXRqvKDKbdclFdqnbOUjg7Swm98WZfIjtpgM07gvjo2K7O4kzsl3V4+65Ffd00OK56M7BX9jblYAtgdIkeTuKOoEbBtyVHb4AfrdQ0/HvCeKF9zofa8iAtX7S0MSheopMl6dMOs0BUkfkPuj0fHn+8fJFieqo5+H8jqCaAAH27pCrQFAS3EJybFwfNXThhGUTl5CLU7giE+tLlwaZ+zms3vvRvLr2BTm+xwGjMKroq0EkHDbl8="
          - name: "google.restrDomain"
            value: "AgBsu3v430MDkRFDYh9CRrBg7OPxtWwE4Di8KDfeReDHY8ZPmkPq4zML81VI+xku2N1gh9c+Bm6g/z4b8L7sY/2oiUx0lHBpEdnN6Rle0hUBKv2IcXuEUDbAYdfmd5uvFJ8+7M8sJpypFxSBzv7sjehD1R8eXjMEKodTCtA1/f18Wyvrhd6SgR3x7y5CJ2sdQLnaorvbdZmkgFK1BxIv6RFXss0+tS08aXs1A4Ka4xZ83Mn2vicanbuCm6R9CCerLpXpkqrH8rd1Dza+ZN7rV+8LIEH4oFQz+1dwWdUDUvSpaWeaUW5+Fg0hlAREi19o5WcI+dAPHOeJjVH+MtHqWzRyHXCI6M2D4IXSIZ03cPlOH1+53KI1m/zzIWRzhsQDh++uFoKKI8nZW90hLrISFYcFI3wRa2YwoxYcKmdPGJy84tCQI+Sp6OGKeByoeyRsovpSyXKd34NT5fFTJU+udYFhfYHj1HEXtq0qWHeZsreRjAxtP5/z6Mvd6SWrKrTTk/fZ/xjHwTluVjOxaWp7ozu4gxc4wbDbI7/G5YmjJhcHkKMAHqCQCgqVfoxaLKBKZ+vzhRI4lejW0wMrQYABpS1xhkIpU1W9PhGfy55AxdN/IbIPTmNzrEB+kUVmqqO885Dw0rcfCLbf5hM8s5ecFyjtg7TV6FCOTl4cpCrLMFCPliBLKnW860QWTFkWk7XyjWWoUWA8JxmzN4lRHVA="
          - name: "google.enable"
            value: "true"
          - name: "git.clientSecret"
            value: "AgCpLiRUPovmu+MddZIOASTrdlO/IS/+0rLr3TASDHUmG6v4dPMDhkuaJ6tfoOkVDY/qSWhU281idZ9Ha42VB8nSlqGoP2WlWuGxNBQCHNaPVCLNXCoZtL5pg0aLjtO+L3mKjRr5ms8DvWyBs9S/z+YAwnP133jwuTXi3lyffmR0m1wBh3RhnuVSVXGGmWO7YKpPg40yf/xmfRv5PwDR7bSSYvO7jemLBSPZq/K6bRyXucS8gvoZbFqoMXJ/k1whYGsbwmCZaYV89FrVLRUsjN6Y5/sB5YJWcJctTcE2VAzhGShX56IGUZNdSFFl6YE2uRW9TtfahTrq4UNj/CQCjgBsHilRZukLTY//x6XsqxYN2dCIG5LtC0j6D23SBc3bDJFzElCfBbptewv6I/4F1o1GRow8iFcCoB9h2f3jirS1FU4OQO9xx9l2gyoCpl52gEo/vvF9WyF8HHVyPWTbrRzZtXWthS7SOz7oKJGtJ6HYhNRnThZDqkc81SDuGgJHVFS//1D+Jz0Yq93qCFkVBEJCtO6vabYogCQZPhHO93N+z9TAIt/e/OfDXqRKkDqmf8izSkiaGWio058NO402Yl8MnLHFmhuOJ33v245a2EemmpxGrVE34d5peNN73rDQaGSHtP1HHLDLD769DHN173s08c7IlopyEwymMDQRs/kW10vnhCwDJLCdEOL5GGYFMFf7WrAui2VbtyIBxKJMg+HYqFIV52BCNcm6iS33t/qMJmrcIS6AifbX"
          - name: "git.clientId"
            value: "AgBUogD4lelhqme3Yqfpl3PVgKwe7YTMUHbqZRJeY/vgMRpQuvyEt4Bn+676kuKAVb+P/0/NVpIx95ju+a64rUKX59B8B/M1ITnTuzbkyFFEZaDjZSxrOg5l0vyJZbdgJ/PfviyP5kQy4VP3++Y7rFNc63oJE47Wfhlw1hnm78+lrWcqvuf6zxItgTEwMAE0UM5nr69KLG4+I9KkDGziVR9Y9DfEzQslnHXZ8b0Hdf3XNJZ38qe5xBvvwPiADOV5zaOmFVzvGWACgPXKQBPIbhVAQk+uNGsSo9OnDueU0RB1IceGBnqwqJtiL/qZ+Xj0IxDCM0XX8JnnZD+Z1j05vYEISXs6PESsFsn7DCuvCX3/E8QjRJRAfrRKEIR1XVwyTWv3kjKpEAx/rHPhk2rz12cIDkXuFyIjDyjZlwKkngEbTh64dbPO2jX7XC7kA4gik3PpVOCOv/2z4u0d2ckzznZzaJxXP21Fz74/RYWbK0O3NgDvQNlJ1BA9cLRixu3b73jEXdstAs1eF2qTeZ7EN6+FaaXnh/vl3wmA5eps5NH76pfEF66FIcra35yiPhzItOvHhcYPWxX3Hmam5AqqZL36FqjvUajQ5A1Nx3Laj0mT9rZq6JmdVgiC5w0ye95ommDMa4OcaYeknWJqopKZ5rKTuDjm8ySsgJPKClY3nd+KgzhUV9umwnD40glMi0ZPmhHMPIaog43v6fjwll8j8RTsHEY11w=="
          - name: "git.restrOrgs"
            value: "AgBhGhh5F9J8aoAf9spX60S+k4+HUodVRGo0X6zBd6E9VGlmcbGTUfti8+ULGqi9NBJ3bCAAHPJvFDe76QJOaQIS1v/oF/0H2gyqOBMZjTeOKu1cOux5tLVaKoZlkLDrcvoodN4eUGIH+SJEV+ZuHRxNV08oaUhG2b/EBsUg68snhCKJhcNd5q1S9KRykT/YBz6ZCLH+Z8lYd/eG7tWTgyma/9Pfc8KufJP7DmexYovdjJDEu3V+EdR/lGa0ODY2tluYCeAprlqBuYKjoqit1oaxjgHuLEhwS+o3Y2i3UTE9Mt/Ycrilpqoivmd/GsJFINZlIV1QCLueXjDbJ2mrO1Te6yb5xw87XXBjyHMtGhn5e8g7B6pZL0I//D64QlRSoaChBJjvRZljVX96nH0WiCuamSRpZByHRMA6z8aSOhtWb/lB8+xjE+izLfs4mdCbx0FFh6EzVmw3XcLG3qxQi0bfilO+1FPLGvZVwq9qi+On8UeUldQjvg7GnS6mhYjWohI7iVvaxDR4Pz83r3HtQUheqJHtTkHoZFOR3P6BVGgic3nJIX1pLQjZ6FZbWkbukLBMW/G+xTyDLgtl6QsCy/tOgW2VykwOHeUVxbzKmRYTEeBp69HuJWdL3p7Q6LkFubMREuZhn0KKD6oP7i1AYlqYk65otrVzPZikwIoQgg2qQEiX0RgOCvhOjmape4h78l8RJHyVhDuo41YWXqujUpXdIXyyFw=="
          - name: "git.enable"
            value: "true"
          - name: "htpasswd.enable"
            value: "true"
          - name: "htpasswd.data"
            value: "AgAKDrNtxXyshcqK3/NHGmTYKQZuHG1JrRDdO04XQxfIIQsCQAKbhsgvV+ML2tqIG7F7qg+4zNVM3Z6fLtNAnyHZh/acTVN1V9XxB1eW5gNPwooVVvET5Nr2ivD3n5vIuhASP/bWzrU4w92T7Ha3Ghl8WofypDwYuT6wIvSL3FcE+PelJYVJkyufQ9WNM5vmaDIEEkzWl5S4CJikY1RlGPm7SkkXFGRymPVKj8/nDrybjFUTln/HogMKiGNnwOg36q52HTAikY9jPGowJcfFRgeMOFgh3yu0RimxgG0ZeheF4DrxxC2z8oUrLtot7tM62Fzy/58hl5cNtU780qW4tu6MdeOlvhP5WBdDB81QBORxsp/+ybPjxtiZFvLB+FaMJkzt5K5Z0I0EIhWeNetHj9bqb46c/ZfutHOxuJzwlBgrGBSBvmstO7nVax2f2kwP0GRurcIBhLXfieROU4NGsUJcQnKavXqFpxj56uAkB3Fa7nmfAp7WGLlt0iV9dXkggCm7N/ISHVuQQkWhuZtqZ5cpriQbjac/oCHKo4UV6DUO3dQnhFq3JT85tnL2nJpPg/kzYeHgjlKS1Vnh9tts4n9yjqTzkV5xSXJ15B/gOHLbtWW12Tf25ly3bHqbQ8wmQm4C6egLT+Ffw4ldLfIYxdnIZCcXdVOZWmD7mOKbdDI3o7rXefc6gpUnOxE+e1/D5IZq3GH0szk4aK+izx0pIv2ILKrhnRHMGgpbviaWaNcvmlG9UMQWo0EcJ2Rxs8eCf4RsbEgosXF0mwQfcyX0cj6Gj0mEB9s="
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

###################### OAUTH GROUP SYNC  ######################
  oauthGroupSync:
    name: oauth-group-sync
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gp-infrastructure
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-chart-development/"
      chart: gp-oauth-group-sync
      targetRevision: "*"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true


####################### CLUSTER-CONFIG ########################
  clusterConfig:
    name: cluster-config
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gp-infrastructure
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-chart-development/"
      chart: gp-cluster-config
      targetRevision: "*"
      helm:
        parameters:
          - name: "argocd.workflowrepository.username"
            value: "AgBqj/p+6BNP7TITeQyttPY8QYW2RkY69sV1aHWvR4G4/meMdlEQcKZEbqcTRb/20WypPB5DE22flwhGU/K9n5Dp3GMrkEhAEI1nOuelwmKiPkgkVz8r4JcQsQswtW+4xpPTFe6JZJOoCRd7Yx+wSeIZt8Zjsy4Iz3fErx+xmMj9yH60bLiepCVLKbhuER4WqKrr7jYKICS1M3dTWaPlIjnmXSyyy7vrfl7iK7SATzzya9zSOy9FVLEvjUukPOo5out5bEhbIEdQ8z/x+CucrNcqYaCWgRe2sks7OqevzHxl9eV8Qx7OdSCBvs57Zwf5QDU8X7ls4Yy4+5xHiXS0qF8K5ppFEDWBoMrCV270WjJELaF6/vFCTAXB//WlZ377hgPWQWlU4bhxYT5D7jLQ7FZDt6Yi7zIZJ6GBj1rfp0gyf5MWmBkzBnDoWv3SuLlqWvNOgQAaWZc7OIbEkSMyIODbkU5H7WSHlAd2z/4QZ27DHVNV76JImunkxNIfOvuEQjXp0qIqVpz9er6gF18VHQ3ksCD6ltOwpBdkddVGg9dTXe9oawSxtfVpMObGnfFJ81e1mWxZrIB9xl+yftFDcS8NaDM5IUn4/GxieSGXQelWw58/ue7PtjRgIhgcmUcIomNu+9tRRwQQt9n96vA6VB17VA6c7lOXKiAK/aqaiS4LaLTkl3D6moN6+c+F41LbW1e8lo3T6IR1TUdP9KpdLdC8Sw=="
          - name: "argocd.workflowrepository.sshPrivateKey"
            value: "AgBk3KpCtQz2o1z78EeOTTrbZWmWKZHzgXDtSn2tTyAoQpF2kYlgj/e/zJK0Vo0Ij4A9zK4idpgZL6WmCeEq6AuGzly9pVM6/CZSZvbsVd5xvUg5IcvGtFG1mN4/ConlRLqXoOcxT4/K1XuYYU7zvoDAKGihJtUa+ZKS8es0lqcrLoBA3E9ucwxlr1u8LaA3xRp6/vIs4eW0sxVfop+Dt8fFvhjSHvPX1D2vKqf37f+omDCwmcJmJKOPOmPGWH6X9EoRrZnVXK0SeIWgqEWNcaC9ImiojS5DZDlc4wH1WiAPp3iuVzSce2doL/FZtyMExO/uZUCw7G9MxcZyyolTYR9LW3Sr9ywJCcpk8PwOoaKidQKhp5ODNVLU6yx4EAFCEV/F4lEFYQ+Vrkqfnzkl5mDPic/m3X3sy+iJQzV7oqs3u9GiO64/U2aFSzMyfn+WVhAMEcPyo/+Wv7yQfsiCpqPBU67R5LvS7d6/IWvAjsXf2gm42B+KGcH7digTTu2hE293kjsKSd6d+DYLPdJaP2gBq5mo/PR9LuhN24NARPpq8/LDear833y+Iye3FWFnwmQADDuBi5+cmt5eAqn8cvIczdU3TS/z270pj+I9d0qmrJFxDCA9c0sc3V56HMhK1E7B4UOZ+Psdfsp8EHnIVUFxKmw3BBool/8tYdhU9DRk0a4fvKgycLdljKsZoYKpcnFWQ+hfiv56bYeMFCnNBLrhfMLhi7eG+L/IbHlXAuuj37OtirRlD6nAvLSGq+u0ep8xrR7tPX65SSHNs7Xqten/Oq0nLOBDC0r/8tHhyDIA/Eki5tpOrx5efEUgtFz2OMSyMmg22y0HCyZIfwhpAetK/h6romzZ1ijDB5TTykGu+++Kc1vHEvHblRNrCUQ5njQn09wfvdz+yHq3xSlfUKcvXd9uS2qOwrnT3KepWggrR70Beyd/9gPWScIxoZdGo+O4d1FObHlQ36KHoez72kyM+ml2+EWIJlvn/pMy1ame1dNnRyO5dQWatmq410XVBruKNOzaxl6DHKkk0WjQuD1io621OFwvZQ96AgS0oysUn5lHEWNlDhBUVPDhD7JQ4dyp6amVv39dHsHahLaru73vd++I1HPmEQeT5lrr+mN39pXm1tWUCnn0zwLjy1Rl4K+NKtCGILT3wzx/T85gOZxvaAO/5M2NHT37NQ94s+xn54+NjvFRdNBkEaatfcVhIU1xrUdI6xnzsjJe2jiQF/m7w+tJKkqRwVFOXgqTMi88XoShGy7RvwUinaNHEgDyaosXpGEr4FWGF0aTmDFBh2XbxXZda4LRM2NZQpTsPdm4T9Rh693sV3EkeFhOO5OPQcYngvf9pcL0QMj1AiS16Tmx6DP9/WnQOTnfyw54xUZbXNj9071SybUXgnpVknqwFTBPs7DBZBURucprxq5OnzK+uZtsZGzNfRztCfc4moSq8q9QJLs1zAo7RlTN88tcu/sKVBNXkgi7FdyHCNc5ZkzgSuz9GgAfp0LfQn1SzzBGM12jnTnjSAjOahAk/CfJvWKwM1MRkh0YF9nAVPDlcxSo7BDoVPadJuSa8HpZOxelEoqfRKSUM3HyizmittfGE/iZjnuPSsRG7QLlvJG+nC8uLU7mxya5QOGi7imoLu/9PxgWDyTniTNDsALz5i5xljQv8/2lJdoMcWukNr1LOt8g202ZqhmDMzeA5HsqvR63Yj1q8pM="
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

########################## ROOK/CEPH OPERATOR ##########################
  rookCephOperator:
    name: rook-ceph-operator
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: rook-ceph
      create: false
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-chart-development/"
      chart: gp-rook-ceph-operator
      targetRevision: "*"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

##################### IMAGE REGISTRY CACHE ######################
  internalRegistryMirror:
    name: openshift-registry-mirror
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gp-infrastructure
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-chart-development/"
      chart: gp-pull-through-cache
      targetRevision: "*"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ##################### CERT-MANAGER ######################
  certManager:
    name: cert-manager
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: cert-manager
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-cert-manager
      targetRevision: "*"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

##################### CERTIFICATES-PATCHES ######################
  certificatesPatches:
    name: certificate-patches
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gp-infrastructure
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-chart-development/"
      chart: gp-certificates-patches
      targetRevision: "*"
      helm:
        parameters:
          - name: "apiserver.customApiUrl"
            value: "api.play.gepaplexx.com"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

##################### CLUSTER-ISSUER ######################
  clusterIssuer:
    name: cluster-issuer
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: cert-manager
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-chart-development/"
      chart: gp-cluster-issuer
      targetRevision: "*"
      helm:
        parameters:
          - name: "solvers.dnsZones[0]"
            value: "play.gepaplexx.com"
          - name: "solvers.accessKeyId"
            value: "AKIATM2YI3GT32L3MCWJ"
          - name: "solvers.secretName"
            value: "play-route53-credentials-secret"
          - name: "solvers.secretAccessKey"
            value: "AgBmrS2xjLpOxgtixLWd+v/F1zKRHhF0fHxDcx2oehxih08XJtNM3AK3sCuAAt2uOCpSNkh65rnP/TVlSdmMIB6m/7fKLr0g8nYl+S+tt4upgXSl+uroJKW+nEJXxJQ3EtFhKkYZ8tZ7N8dSfudmSbh8XEy0xvvyyE8/Zy6xjskrLZBJaJDrLR84F/ffaImZf2i/5L98UCgynbHWcUQjNGUsU4rAozxp7v1wNrka89ZPEPLj2xWTFSwUsH8UEP/SC4p2MC1mPUyxgqm3D1hSxp8Y5jiFGZyowd+KWM24XZJrW8L1DxK545uoZK2fVBpNSkQwNacOoidWUOfVElbaFFKgSlrz1P9UjLzPIfClnYvQio3eXemkmco2NbgsnG6sf5YswORBdUPAJmLLFJ+i2oEVOABkONngwQ725Fy0ivzyt/c6CKhww269KKV5uWQc+NGGnB2AljujeBkkj5hsP1X61ApoquxEvIRSE4XJ27yDXvXFQAIqfjnEmtM7bh4VN7BotLdCSFyu3hnW6AzNjIaBVD/vhF2KP+GMAOSbBAxAEdNlmgJBzOYU7bogvL8FRfyodGu81BneSUXdk8ODKZ80dTyXVt28IGXXk8WEOJaWrKQbgHXK9F8hadJAbzVQ7EtH6Bss4K+13OnId75cm1jtncYo3sNo9BkBVO5G4ePh948PppZFcs1Z2I48UD2w49YaMQcu1m+8X1U9jmwMez91seh2N22xlyOWohu5tc2xpZMioYwjQRTJ"
          - name: "certificates.defaultIngress"
            value: "*.apps.play.gepaplexx.com"
          - name: "certificates.console"
            value: "console.apps.play.gepaplexx.com"
          - name: "certificates.api"
            value: "api.play.gepaplexx.com"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

##################### CONSOLE-PATCHES ######################
  consolePatches:
    name: console-patches
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gp-infrastructure
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-chart-development/"
      chart: gp-console-patches
      targetRevision: "*"
      helm:
        parameters:
          - name: "route.nameOverride"
            value: "true"
          - name: "route.hostname"
            value: "apps.play.gepaplexx.com"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true