project:
  create: true
  name: gepaplexx

applications:
################## RESOURCE LOCKER OPERATOR ###################
  resourceLocker:
    name: resource-locker-operator
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gp-infrastructure
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-chart-development/"
      chart: gp-resource-locker
      targetRevision: "*"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

################## SEALED SECRETS OPERATOR ####################
  sealedSecretsOperator:
    name: sealed-secrets-operator
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gp-infrastructure
      create: false
    source:
      chart: sealed-secrets
      repoURL: https://bitnami-labs.github.io/sealed-secrets
      targetRevision: 2.*
      helm:
        parameters:
          - name: containerSecurityContext.enabled
            value: 'false'
          - name: podSecurityContext.enabled
            value: 'false'
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

###################### IDENTITY PROVIDER ######################
  identityProvider:
    name: identity-provider
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gp-infrastructure
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-chart-development/"
      chart: gp-identity-provider
      targetRevision: "*"
      helm:
        parameters:
          - name: "google.clientSecret"
            value: "AgBR6/2xnoPliY7FBmP4dC+9QvL8p1VjbHWq74q2Xjr0sZvtmYJchEfJ9PiuT5nyrK9VsBpHtbxbY24xRIoyjT6j6bgnI9epwgH/UKdrXETVfyMHxGjIzsk6eqJalKJKKdNqK+YrT6tjwo5pl9dxWQu0JRn7BOw+ovrOMVOY3yVG3sMK6TyPLzimlqeEiBWSBvwy67eOTy7iuo+jRrsKmgnrXoa2c1EdgIF3Uq1QT7rz2peoEoiQ9g5pEEJaf9eYcYcU+SZbxMGU7XlY+ma1e+d4iRJV7TJboWPH0s2cIhx6kP3sCAeX+iB1mD/D5EfzlB1C+Vv+ixfIUMjY7MB2DOgfmw3bZM0CV9Ke1eEXfnkwQJ9TU1tP859uer22bO06fC+F7PyFAQEvwM349mr11pZn/SJTkyrCtZDSwmxA0HQGPqWtWd9qaMrPsFhU4M8fHW/sV88KwMj4e3vx59Ni05oeaoEOjJ+yzf1k/OpMVK6M7REqVK2FiABrCCi5xlbx/JhrNMG28AmZXsHryb0Y7dbSxXhB2LSg4KRpt8pmrpeXe16IfQO6WReveg4pCDdG2VdETw7mHfaGlPgFNyuV20Wf8ozq2gW51PDKCOBg61w3Il0yAvQcSxbr9EE9zHkACRntqSlbx8dMVu4OuD1x1VapyRlUk3/obYxfTeDqgVzE2wKHVMTPytcaLQyydsgCTST+/PwhBqaYzNjNzVz3IBPJxJjbziylG0X0"
          - name: "google.clientId"
            value: "AgBjuExlJRHwWEWz37RUta/yGaq47D529+NNkjq8MtjvDRUy/tGE2Rdw5G9HvL2CxkHCYO+UYW6kM00JOkEzoG7VdDHwocgu2tmhqxvpsmRdg109KyD5BWGmn68qAKE9YdY92IpR7EsC541bAbEfLzVuyLV7ckdvHUS5BdVo1VLXXTt8kE8zDSWR+H0U4Pp8NpPY/FQzLt0YdEtYMlr13sfj1wL2Lf6p7Q/F76sdl6zFFqrheMLGM3IKgqhzvF0dH1oFQHry5CBOgiRI6ydFsJtdsfzzpkBMI2cTET+wdthIFlQseQm9RtJm44TpBwjTDrV/NecWm4R66wLujeraDpT9AhvdWcGsO0ahKvHlWn7ebdbUk9NDi62Q/T4OrKLXJ12ALsyJHPCedEQO5tISUasrYRXLKqMbY1FGyMpscPOOvLqI0gw9QpFN+k3Xahb9WS1LCCt0OP0bel11XVl0US+oH+nmltdL7cEvFUlzikqqSi5FJ3cMJ2IgAlmspyNVR3/CHsDUtJQ43CgWnYE3LczD3zzNcO29QRoOciVdphzdLPKtOrxkv6/TsASZzTf9zH5mGSj1GXAu+cf2W2j7LeVUZGCxf+kZTf5Ccy6CNw/uMz19uUJXas+DTo9XK/3RkTG3JaehyfIgH12SnnfGF7G95CZyDx5yorCfW29q4qssu9Fq15nXoP4h1sa7DbAO1M5jnwAC2+1orTgQAC13bX1pNakJo+TwYMqUKUrE0AnK38Qu6mZmE1WQiT4pHh4QMK6/zup/67oHL5i5IAOceM/FQpDZqEb5pgD5"
          - name: "google.restrDomain"
            value: "AgBTP8zGqpaJTA8PMYtlHYIbQ/0BrgsKpeyoTJWWZFvByrzV1PnpXIEyw/frU6N4+A8DXAkLC4CmiXgRhAsKblNPCCFape4pTQLM95WhxDsXXaTKim3Bl5HTyoEZ3J3WZ++61XksvR0qARkK4KNpIDlKeyBn4nmQPgJz7HgMWXMHnTryGhHqhXUCVPf9MgdrCZDDngbOQW5HO4dKJKxMH0QOjV8YgiyQ6aSNMWgxdYS+Wii1EbASE+flg3nAGpJTrLcNr4P8NZpbs0H/OPS0VXvbh9cDP/RcatSZ3jg3kDptrAnWw7WswA/G7apPrFcCrc08LvQglvLeyBMuEsZ5DVStX2uZBKsJm1qbbwVfrw7Je+3GcTHx2l/zoFULj8Za9IeewmbAngeJVVLQ9cWm0PS7lNkNF2112fq/x0bdxoZwe7izilFj3mnHkA0Zr7Ztx1D7WFm4cXNfnlMmrSHXOX2dGLwWRjdiAg0Ziz6DoSgezTyJrWsRxNnSJzW6L5jYA4x7zJAu0f2ofL/AkvrY5U98IKrSpcwWk3tPZEcUCSM0NSBsH/Iu1SZQUKQWwd8lEZqAeqSPdvUyQOVHbGjmZDDLk6sYul4LkgL9XNjKYcsIvEZjXwuaeeu2KSCRR8gxP7AVi3wVMzIWm8nqSWxQQtsrodynqVlfxl8HBkMmlYiquYXhn1mo9stha/gAcGXNRK/wk6ZdFU1Dy56DKgns"
          - name: "google.enable"
            value: "true"
          - name: "git.clientSecret"
            value: "AgAUbFTUudYvzAStHgXXygwbu08sR4FeOW3vnBJ6rHLJ2QtaJ3iWoPEnGAICcBhWn8cc3pU7JA0G0PQORmldNH/inkqj3bEZVush3WWoE/NDKqlMujj9KmOzQ13Xd4ISDIFJ6u1cjYoZQU0oKYA5PIas94q5E5Zcssj+MkpsIAg3BpPxgH0+5HU+wGtWVRqG8wvBJ6HybCBQLrl+wdgIHjTuaXCfPnB5AKXRmD4twZ0A2hduO6dJ8hMx6Y8cI0QclRrtIfL7q2Ip3TvDY7C+FcObfmYZ6MdPhlMMgNkDlcPMLdj+D80HYdx3QHZgTnTbZRNQVvupzCx0GGeLhTK4ZQdxhN768KmEqF01KRu9Mhh3hkXjWp9I3oPprMkzlJrYtY04JqjwCAdh8hbozolKmJEgkWXJkm1MdZr0X4+wZDOzz017nQyWSAjrUqMqE5G25tiZeHcLAaO//7GLSq5iQATYp9ty3/VFceWbjtHVpFr9EuQ0GQtYZZateqG6xEJ6L5K1WO5hTgrFrGkZDagmt9q9C2BTHzXrQPQhGtKbS/JF+t5y+1vNHzJTFIYWL50j66ARMlyFVGQ/HMOGCyuPdJu9MHXwKtPd5XI/Xgi423G/ILPXYwLtGjmyv/MDcrRBQr/1qwEfka3U1k6FjK9hWOHsVY2YdUNV0dSKIzPgBYal6vJWJ3beon8iX8/iOaQF+CLAJntlxx3QCrarONcSxCYiPCKOwHLXoaPGqaxUmbda2fw1rZAoiosJdg=="
          - name: "git.clientId"
            value: "AgBnclhFXitvpVoNcNhsM/4AI+lT9lfPBZQ/xRNutGZ+Kxuz//o7w90WJcTT4UMEVMrJAlodPPCcz1YG1fApA0KmAHYa7e2mUpplSPCnD2iQ6laArtnNUy2841Jb0dROx5LutwDFDJtq/VNxuHQS4I2OtGjZlHrled3bjkxA42OVLlxfz0LgTYm+hSgmbyMUYDn9B6J/3xOt19Tz5eR4dyhS9qY0P/AWggLnZIvoTa5Ri5s8d879MV672UBBefQgYpR5m0kQtRmJAccLqQ40OyFV84NsVzt3E45OyJOvjCWVmk2p++wp/HWnu3Yeq+2gaP+FyjTIdb+oCf6VPENe+5IuDK3LbvAMkreX5+wIVUjXTSzbWEdGRLe/dA+S+2w8NqFup/vGYv4WOEBUQyih13uX/+4Np8LxYTVeX/gSDvRcBXNfanOMOz5kw0W3tevnKoBGZObLbKKQlBckO3SOZlX6lnGsgMvdlf4i5O38/wee4/zFC5VOUACeovfn/edZANpz8hiCmpHTvGPHi1nVRPlikcruHMK34/uZSy8OooHO/4/natlbXJopTUNA1Wo2YFMvKZ0lVgOB86ByU95qay7NVfViDM/n29jcc3c6sGfaIc+3Vt4iBUtrimh1fLV2TEngJL9TQhAGAjWq8Yk7Z47Bj4yxNzZHU6EslTCC7Ji1AZJnYVQn3+yHc4c2Ag0eM+ZoFw+O4U5qPzhiiCxLrwSVPkw/w+g="
          - name: "git.restrOrgs"
            value: "AgALBLY5jJeWPHJAZs+/OcOwXlBHJYoWmFk9WNz19+LFlQv7GICyXHvnwGg53KvBGc0/7irzE3JVfMuc0ab6UkglqiyToATwP+aWfW6Sjq49Van2Lrh1rC78tD0oz/3ZzSNaids6wgzM9lnbfDCI0Pq0OkfcEzGOK3d/hOC22nyqUsqs+MgnTKKZhmFaQPLhSNVN5ZUlN2fGips9m3tqln3BjHLKYXEY2ocz7q8rPNnMu3eRf/n9B36IG3PkUgssRAw9q5ShfD40sb4rsuh5x7QPL35/32GCEJBX5AtfdT4oDZ7sKSb2PHlAfc8+SM3rsw2p0FaY8va2RnOt4B/z+sd7qwD8RfJkjbCdyakPhk35Z+iDWc7nYR4OpQkO0YN18ags9hTBKO9hSS461TxAMhx/u5EWsL/xIJDbs4I9XzyScPLW9XELzFycfnUou7PxlgVjZ4aiZ7n5uogm31E4+YK8uFxkPjJanIwqutkCfPNs3ajwSSrKy9i5amh4piLHfTlmmNGHQiAbEQRM++cF/pWjoiyT+5lv1cVpxe6I4A3V4/b5r7Axyi/95JCNBZXTRNCqWXBUrKxEFU+G5PJ2ohvsgtkwICZBJkb5gd9it++vOApUDW+O3E/lomRhGjgSbsh9Gc4GyYPxaRSzXDCUz/OO81Wx+1UrHoalDiPmeFcZgksx1kJMQOnDpGDlbY6aF2+ZgSaM1wq5G7trEOMDxj2NmBQVccY="
          - name: "git.enable"
            value: "true"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

###################### OAUTH GROUP SYNC  ######################
  oauthGroupSync:
    name: oauth-group-sync
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gp-infrastructure
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-chart-development/"
      chart: gp-oauth-group-sync
      targetRevision: "*"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true


####################### CLUSTER-CONFIG ########################
  clusterConfig:
    name: cluster-config
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gp-infrastructure
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-chart-development/"
      chart: gp-cluster-config
      targetRevision: "*"
    helm:
      parameters:
        - name: "argocd.workflowrepository.username"
          value: "AgCto5xs6ow513MAasHFdvvUgGdNWQMk+/7RNuLNdy3KsOA1DEDbEO6kcTuFw1aRk0Qks7ncqqYQ1d1lgm4mnPa2++ofUh4qHSgzFrm82DOpmKhEHxG1REjHxfsjhRxXNMbYF7J/TXq7FHJ7HUDM2TvTxiaYl5nsC/6cQmZeHeELGfzYPy/VH6Y1Z1QgRev/myOL/8qvavK7uAfcR48g8tFFIzduUfpNZOOwYIY3TJ+vQGFhs93f6z0gOw9bA0gGAAPiVXS1foVRXpb0NUr0tF9XAQAo2qxC3TvBykrSR+y1LTedJkqDWFucXveMUhqh7gO/hw/z7/l8obT7iGFmGl55QsygLCN2+RohG3V7Z1k++GXWBxwk1eDcm5s9s5BMgDqjs3/b7FLQEe7LFwc/gSCrulGsnYOOsP4/snp0xUtkXiVyVF8KUeiw+UPfz9m0u3Z9FTxpT5F3RD1HrrcGw1yfQihf6x1G2YBsul6ge8s5C88htjCdtW9TZj0EG3VXDnAlGi+GhBHwmtiDDBKwlVNfKj90lIKfjGXsdM6bvyGAg7xf/mW/2Yy17D76nnyVMsIifAIrNtx732J2+2N2OWLDe9bQfetGKK8lsFynvLEZCo7bY8fQSXuYroLcZfzBqF1Gw47vSwGdVG7mAL90XrXiIw5iQFgfUHK5tR1B+bPR+N0rF0jzfVsuYhtE40uLkEQxMOV5Ti8zV/PwNIIFtDI//fopu3max26G"
        - name: "argocd.workflowrepository.sshPrivateKey"
          value: "AgBUHaZ2Tm1JDi5RUX+roGKc5qzZdGxEJppupx+V8HYUyC+GT2L+1Tkq7CBsIGnnLgZJC3NrZHm7tsO8uajERm5uOVk4rPDcCB5bki17gLhc1O6Xq0iRPoPqGP2lX1qA/qZTAkgiS1KGlkAasR7BAnB6SBjJrCuAEQD8t5vPqWT1pWNi3ZyotrMNrgT/shbjR3W6L2HcwKs8WEAcZ205onKCc625RFGg9JaUB8Iv/RuMvfmQNqT0LYP/uWzlxoqUpzx6uXoa+5C7fKTapI611vCUE64Uihn3KTP98gNPA784zuSk2Anahg/pkrioLsTFGZO03oCQZAXa5GhsuIEIGx9GkveAmv00MLcPJj5geqQeC0t+PsuXBL1LAfRZMF6UJz/VWvTQ+R11Nk+Fe7+tM/6xzjgmSaUZN7k4deevxNxdCk3qoury5mViKWsJeKNInOKDj69tA6dxFLsH95FwXGHhdcZxTeOxBu5EgE/jALyggN2R6PiCQ6su0CchJGK0IZR53B5mECjwQoEReuQhBkyofAma68qVLh8L7m1Wozq4XJlCu7MMIMAjKx63Onwavbn4X50zVBYcIu8Oat1lygfjJPEzy76xdmgc1PvRDb9dCIoDfrfEhtUB6GifTdGEvsmcwXPPcgNTq5JXr0D35PNEDMfqy8re4KVRbZMhbIdFEcAtUqP6bY9Sv/PXvihcBld7M6djOG6OjB8lJU/yGs+LmREwYa65+vbDKbR0xgWeBAyTgOIfRYq+7FytVHIePHHmkac="
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

########################## ROOK/CEPH OPERATOR ##########################
  rookCephOperator:
    name: rook-ceph-operator
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: rook-ceph
      create: false
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-chart-development/"
      chart: gp-rook-ceph-operator
      targetRevision: "*"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

##################### IMAGE REGISTRY CACHE ######################
  internalRegistryMirror:
    name: openshift-registry-mirror
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gp-infrastructure
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-chart-development/"
      chart: gp-pull-through-cache
      targetRevision: "*"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ##################### CERT-MANAGER ######################
  certManager:
    name: cert-manager
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: cert-manager
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-cert-manager
      targetRevision: "*"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

##################### CERTIFICATES-PATCHES ######################
  certificatesPatches:
    name: certificate-patches
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gp-infrastructure
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-chart-development/"
      chart: gp-certificates-patches
      targetRevision: "*"
      helm:
        parameters:
          - name: "apiserver.customApiUrl"
            value: "api.play.gepaplexx.com"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

##################### CLUSTER-ISSUER ######################
  clusterIssuer:
    name: cluster-issuer
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: cert-manager
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-chart-development/"
      chart: gp-cluster-issuer
      targetRevision: "*"
      helm:
        parameters:
          - name: "solvers.dnsZones[0]"
            value: "play.gepaplexx.com"
          - name: "solvers.accessKeyId"
            value: "AKIATM2YI3GT356GUVVU"
          - name: "solvers.secretName"
            value: "play-route53-credentials-secret"
          - name: "solvers.secretAccessKey"
            value: "AgC1D0QVBXfqKfAsEDsjq5ET9bbJKzECw81Qduncx/yPk4OYFVoq++ETfikPkNHofO4t772CQ/zQQBId4poh+dcLNRj5JpF8hGthApJIx8VKPXerESsCk2HGYQ4UVnpx0OwjadBlnHTGS69kafw02X9wnsSSM1OnkqgJ+B5ZR5MBdL95DaYF+aOtfn75jkyJMsXWfKIrZVLucWKT+mT/ve+T2pDMua/Pl0+528JL5ehBCgAQnLDHNtX9cyu6CZaiKVlpROuhoYMPEjgSPmRT6K49b0CmBNYpuJ7Li5iMMBrX0hbw0SZoT0sJQGtb5avlmAS19UlP+Musr9aiS9r4f/4ZPqj5Z+D/c+JHTAIohygRchPurq3a6Jn2ANeeK9vTUaIdaeuNnksjSgvGgVCqPn2tIGgtMkmFp3FbIN/YZTFXJ69/KvvHuY1DSLnTbgqJhRWjP17GPun8+fch5DQbMNlbaDDbJD06OGqTqP26Y1OYkL2s5YfJg8orU1638W6I84XWnYDMYxSFPsnfuYhlyHHaZLYs0swiLWeqSj5DfVqjzjjljOZzPNnanuozts+14rXr/SR3+XQ4Ule13CybuJ/lxrDSURISD3apXxMCG/yEKak8qSJOFYjnid9jJAuf09mb23wOmysg+3S0OhawQbF0R64TiUDqZ3SLZ6ORo5D69V6MPm2dhiVOBxDFMHpqY9h5UDKQJOyRRQggA9QfNma/MS4T2TPds1yUmi3NIuFEfNwuqiWg0IPA9A=="
          - name: "certificates.defaultIngress"
            value: "*.apps.play.gepaplexx.com"
          - name: "certificates.console"
            value: "console.apps.play.gepaplexx.com"
          - name: "certificates.api"
            value: "api.play.gepaplexx.com"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

##################### CONSOLE-PATCHES ######################
  consolePatches:
    name: console-patches
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gp-infrastructure
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-chart-development/"
      chart: gp-console-patches
      targetRevision: "*"
      helm:
        parameters:
          - name: "route.nameOverride"
            value: "true"
          - name: "route.hostname"
            value: "apps.play.gepaplexx.com"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true