project:
  create: true
  name: gepaplexx

applications:

  ################## PATCH OPERATOR #############################
  patchOperator:
    name: patch-operator
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gp-infrastructure
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-patch-operator
      targetRevision: "*"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ################## SEALED SECRETS OPERATOR ####################
  sealedSecretsOperator:
    name: sealed-secrets-operator
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gp-infrastructure
      create: false
    source:
      chart: sealed-secrets
      repoURL: https://bitnami-labs.github.io/sealed-secrets
      targetRevision: 2.*
      helm:
        parameters:
          - name: containerSecurityContext.enabled
            value: 'false'
          - name: podSecurityContext.enabled
            value: 'false'
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ###################### IDENTITY PROVIDER ######################
  identityProvider:
    name: identity-provider
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gp-infrastructure
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts"
      chart: gp-identity-provider
      targetRevision: "*"
      helm:
        parameters:
          - name: "google.clientSecret"
            value: "AgBhDriAER+Skk0XxmdeKoJgfn94MFwIqrNtxHuttUlkkBdoMyjZdAVgmMM6+apXRFUZ39aH1+mwtNZkxn2n4zLGjXnkbvCxruh5hjuq64m+sInZDmbxqu7vTNeKOUy7VcaoYtz2JsoVRYderanZ65t6IJVygAa1aB7UwprbJ2NcFRtu971OY1b4tVGPc/BMZx8L/1pAyPG84KruAer2GpOdzB0YBdX26QjbXUelCjuQaTzIsunL6UHz5bH1igBadcYakSXpiHyllJ0MHaaSSdAOWPbnCSz6V6tzCRK3eB7+kx3N4Nkld7AbbBBBpxJC2je8JXsZXQtVby4U0M29k2ugBx8Pqfr+/hFUHB+Yxcq0h1DS0oWN676YS2Z/lStiUoMj4umMH4l6MIL5gwhepGiEn/ZeaCFyM9EPQwwY60fLlFYNiDR6yJd7Rm8SwvD9sf8W7JVMbt95ecevZrNv8fqv9Gh+qgT+t/5H2Nhro8vSIaiB6CbguYca9W0IISldw4tZtzNde8fl9J3z8eBWZ7kxRii4KOU4Knn/sQerAe4lpPzDoTBuHokLPEuZ4KowVCthMMzY79a5YlVq9OWtQEKGvqozbXleofJV3Inn5tIhUGL1eyD959YfTSLw8Jf7hkZfhte/XVRCOMkIkG0S1JyG2XsMgM8HAdSRmJe0wnV5O+kWzj+dFThsI8t05zRys7YX9HFIfIfhA724rZ7tQTlvxpKD6k1zLa0="
          - name: "google.clientId"
            value: "AgBXS0FRsCpbYJob1gg7gfavulPEywy54Wntp51W2NMYD0oA9NpBHs84//uF6u1sNZRZ1v2f8dtSl2W66sXLI6PAXkrBALwA9wFAzEm76PXSyVNA+pBqieiMxP3u2y3jw9j+guffMxz1I9Mm+aGIAPft5+BCdZeXRlWGj31XUhzhTBZfNm4qyPQVuW49V7R6UaO5aD4HalvSKH8mohS06hQcAdNurEK8tGgwJfN69foAYF8hC67I6hB2oHjinmeO3dfL5TF6fltYPHLBPtvLnvZEvrrea/+e6Z3nTmJ/98mUrfOJA/lKdNbimsm1+UsRmJRfEZgcZbLyXzfD1BhTQprHB7Lr8e6O3Epsp/NJcfKiGES0RJ9ZqjFCnAmpm02fuuBfv08c6PWcZlqJSRiuNAVTNNqixICyhC5xGaRu1EKvnIu6S212JRrWZnxEkAJ1lShvuxQOgAUipMcpSoJvBbPUp/+3DCKDtqBVvjfVNbaXv/SDscGksesAeQseWdQGChDg7E86I9Qe+NLtd/JyncPFfu72xJ+ZVPVat09w+U7F7ifTeR4eWQXY5B1s5EVKisHTJ+mBqWTLYw2ymco3yp+YhmojWzqKa4k1m6iiMNvegzlDy6GFrX/lNh7Bezzsm9p8SATRtHkY429k8AkIIdpjTWh8Qu5HkWzySqENErIg+vlT3daP7iFdPRFXMTAEAnU6hrxNqV3mRj76KvaKRydbIPEp/Hh9an2dvjp5vBqe2dCDNmU8uO9g3NzMlURUaUqS8HzGsmkH0FA/TCHObTdNIGfYbR0BYr8="
          - name: "google.restrDomain"
            value: "AgBdq2tkOx9B1POGbZ7csUklUs4D/LYk0H7YOJTVJzkW6nfwX8kcqQPTGaba3tJCUsFf2NZW46n2GAjwu7BQfhvGKPSHiLsl6KaLt8n20fFBIirXcG5Ww076zj1EKh0wQwNFTmQEr4dXx/vX3Z2mcTImYu4eXcwu2YV80cqERTdsg8NpaBV17xu0nTKoHxhlJ9YCdzxc19BAeH9FCjMKzCbsi+FbB9FHqFHsbLchBdt7M5LXyRfaT+rx19QSbxcaak8iUD1PRl+z2jt/70c2U7a/I7HpGI512G05KkaQ/gOy9qtYmwqHDwl1jwqmWWCtDjYuR5Oda/oJt9H4B1fUGuUHDgXoLRA+ThAu/ccSg5AYBa9npOeqQmiNm3NpI5DkEOetYuwNJTaDyJr39RMz7W/hIlLF71ZLgYH5KbYgpLGJhmmD4HQGwoZIxuo1pEbIwpgxCdb2Hh18AtMPzHif1NSumiq+FLaKGfKpYOypZNRVJz6Czo/HZc5/yiJzec62zS0VpBfDkfpk0TgyRuEJupxrpWvzqq12wmQ0PtHgOpczvgGfZEOtKF5ugygmtFbvabvvtoOuDT4rQiMi+20VWgJL1q06Vvs9LcN4XF0c3ZoEF1auzwM2xxtHjPQa2INMXnx1CBwzSyT0LdERKxpnEL7aVBO0QZR40R1FU6K5mma0PCYAKRfdOWtNOeoV0ypjmYUeh9/5a2eKgClNXoA="
          - name: "google.enable"
            value: "true"
          - name: "git.clientSecret"
            value: "AgCqn/mMIstXEuUnWLBs42VVObXpFx7MzPNkphejWOhnvNM3nrWQZy3fC6k0lzWcOJzPM9++ndMvcgA2BFeJi/lZ97wjnCizVsJrsLXmDgRgYQKbs24Q52PHJJ/w2TziGeMdm3GOA3SEoMbjznK2PzyPA4GefDjz/rPS1nfrnucxeyIr9jAWL/cohD2Pv2m+3sK+WzXatnKAXYezPWj4vHVf69tj3rCTsxSaKi3Jrj1lec6R7lszsJRIIQdNmf/ncC6fRsI+CCDta8cizxwegOiuC8K9PTCETeT9i8vupwU/VROS6444jyiZva59jBN4sp562/DANJLEzCVl/DlRpQCiEVBUN/sWMiRgu5fn5YeI6yIxs37kBKIvEuFTXZY4JO2DzcKtl/VoiG214TV4nQp/mutpaagaEcrKOaIqXcYPHOp/ySgd/774F9DKGO5KUgj7XJtpmdjWA0lfHWc+cH65GZKm3LVckiicMJfxq/5t6aV5/EPKu+zk2PzcQw+ujFTVRNLDPjRkF2LGP3VXNWDd4ZLTznpslMKmrdszIIsx3t1mK44QlGknF+YHeGhuJZKWagzu1deqokL0v+xvZN67qDSwZjzBINoYq/OcXQ3aePGLurx17YLyEe62utnB6hK5epoKfeQSJULfSNJSHvVFE+OqA+K+rIMEcEc3IXZNTzfrl5gfdPdzVX7owQNhadatKtfqb7wzfNaxYGKnizDY8dVtGgRcHb2Z8C3AxKue/rk/T66lbTdl"
          - name: "git.clientId"
            value: "AgCX8OWJ5kKWyJRmsXZ/fAzVe9TuqDveSrO6tqRwGzMB+b/tusLo4ycCHzJc6hYR4A513rw3vTbI5OS5BTfa1wTaOJcTmGzE1zbZmIpJk5VWAZsENNSqI05lutO3Nwz6WnOHjaZ4psTyj/6JLecLteZxkKSU046Hn2wq2C3w5cC6Ut5VCMF/IPi1Svd8vS/41aUkvxP2Y07ZlMXoI1UU9Cz5MwBpxE+YG3N6c1NydDA1CKGsjeYT/SGifWQ12+yvmqYnjXsvcQNtPVLDkp/0w989DldbCUHUbEcfHc4N8TaFZI7c80PKf34rg2v2pbEenexG83q87jSR2/mpM0cVCH1Suz+nMxFRI73eEftXT542vYm+eKIlfl0kjkdQ96dQ5CLUGQEYVJZvzDRO+nVRauH6cUD8BYlDgjMtelU6MOsGtPzZnA/sIZ5nDPBNy5Nx4CM3myYYi+XnZREjC/9IxerLQEiEHba0W30IX6/1DQWW9l0e7Jq2mWPjwSYFozbSuuCBwaI3fx0pHa78Nvk6yrslqyUGhfbFfcpj4CuiRhIefBvPwqnvkF/wCPI2pNHQXfuavqn2KCvvt5TkTO3gL3eOx9QjpeizRIBr5GeyczFVBu/bLsi7No+gJNZIMsawVIxV2r9Q4WLxtbU251DN+0DWmGWDCQ297fpQ8bwsTolkfPFLHNy/jISdGrYq3wjfGXwJRAlYLw233fb9Qw7Ah4nLk5b4oQ=="
          - name: "git.restrOrgs"
            value: "AgBB44zhpVbncCKsTCuuAiKSf0jtEH0Gvj8tVBX8g9GzoCq0CS9bK2dWtTuwzEF+ZpDU2aE9h0mz2YXwjvL9XuMZWW75Uwo/dNkcLWBn7qWyzzNA35nKhCK5jRXLlj8rxbtN9ZuQdSiEZp7GlTWZjW4prRC/Dtb+PtF55kQwecr1yX+cnojSfKj6MltD842iTALuo1bvatWTgCg4DhDISM6PpwjKHcULjctpwinWN9GM4kWauozwiNnkDoMzG0X8F5d6eDhuHmxFq9jDPK3MH9hD+1vE/1Lay7PCmEatWyJ3nQKfWLP5XJ9yFrRg67Js2I6+PhHRujpYcEVGrtB/3WTLluTLa3fU6EImhVdVMb3qjmgGNZf/Nvtlh2P7N6x4R9OHmAI0i+VUwf+jMCNO+N7fWDnrTklTdc+p9x+6ra+Rw5I0jk9qY2b6DKHewDrbBCBjvgZQhxBTEIquS77y0pPBvR+d1YtJ0KAQTVxUIVnL/CmiegNbDH2Fn7CrBq+RDDA3N+YttO4+7PxylZovqFAt2PiJs1Abt2uDn1j7wqh5q+IC8VE3GwTGZh5NMulnjcRA9gXhsvhbEjmtA4mN+92iZw5eFR0egzdptUfTeuICplj4uzlWHSQ9p4fZbqKbg2aCwlRUucM5P/jkJWXIubXAIEz7fO/136f0Nql4imDdIQWuCCy67eiQ0Fu84GsEC9JsHl2tCASZFSH7miIJiTW9kAIWog=="
          - name: "git.enable"
            value: "true"
          - name: "htpasswd.enable"
            value: "true"
          - name: "htpasswd.data"
            value: "AgAKDrNtxXyshcqK3/NHGmTYKQZuHG1JrRDdO04XQxfIIQsCQAKbhsgvV+ML2tqIG7F7qg+4zNVM3Z6fLtNAnyHZh/acTVN1V9XxB1eW5gNPwooVVvET5Nr2ivD3n5vIuhASP/bWzrU4w92T7Ha3Ghl8WofypDwYuT6wIvSL3FcE+PelJYVJkyufQ9WNM5vmaDIEEkzWl5S4CJikY1RlGPm7SkkXFGRymPVKj8/nDrybjFUTln/HogMKiGNnwOg36q52HTAikY9jPGowJcfFRgeMOFgh3yu0RimxgG0ZeheF4DrxxC2z8oUrLtot7tM62Fzy/58hl5cNtU780qW4tu6MdeOlvhP5WBdDB81QBORxsp/+ybPjxtiZFvLB+FaMJkzt5K5Z0I0EIhWeNetHj9bqb46c/ZfutHOxuJzwlBgrGBSBvmstO7nVax2f2kwP0GRurcIBhLXfieROU4NGsUJcQnKavXqFpxj56uAkB3Fa7nmfAp7WGLlt0iV9dXkggCm7N/ISHVuQQkWhuZtqZ5cpriQbjac/oCHKo4UV6DUO3dQnhFq3JT85tnL2nJpPg/kzYeHgjlKS1Vnh9tts4n9yjqTzkV5xSXJ15B/gOHLbtWW12Tf25ly3bHqbQ8wmQm4C6egLT+Ffw4ldLfIYxdnIZCcXdVOZWmD7mOKbdDI3o7rXefc6gpUnOxE+e1/D5IZq3GH0szk4aK+izx0pIv2ILKrhnRHMGgpbviaWaNcvmlG9UMQWo0EcJ2Rxs8eCf4RsbEgosXF0mwQfcyX0cj6Gj0mEB9s="
          - name: "ldap.enable"
            value: "true"
          - name: "ldap.bindPassword"
            value: "AgBO1NWT87dkOA8eMT3YaJDd/uDwC2UWLykI1NIRIYGuvdYYCoql0lylACko8ayNhT4TjGAvsst9d7e8ktmkc6SwaVzKk9PZkgMgstQmrpH02iRtRn0Kcj7F4iDisGSLH8cbPXTQkF+etYwsYhPvHarURNw6zvG3X36sCXwhScBwl6QG2vH6fyRHBjvtfs5123T2WRV1R6GfYsUlXpVBwtt22lSYSaRwN9MZOm72LZA8Mky8WE1/ibwTLqxD7Z9EBpmcb6zQwDJzsJMdtsSfOmTyfZmE0YbxExMzcy+lEAGRE80MpyFSHL7xI5tvriHqn6S9kJ/8EglVRMWk833qFsJ9aCXCJywywc4d2L/W4Vcf9N889yx7WxdMTmcU04SRJCTNSldtnTPq+cFS8zL51pa7C8zgS6F+BFj05TslNjsj0KaZlux8oZkOX1nCHzakaNalT5wBqKk4CiwEg0sNUxCd9/ImmymEYy6RbUzqgWAutntdgUzXlQ0z6N0RfOxZ8KfB/rRdle3S2O/AOjUrqFc7WPUjKql+LBCYeRzcKdRzeppycp19ipPW7EUflCWLJW0m1xNPGZ4vaSwP3/ztqosyWine3+bBCFWcGaZbKl+q2DuFFTPHLCYXT6J41yI0goejsYxzpFDkEP89tZbuGlchqG1YGVDKtl4s6iG4DirM4CHEEYUsnmKo1X/TDQkSoRqA93bJXqaY7VqNWo+KFw=="
          - name: "ldap.bindDn"
            value: "AgALBZgG/g4gn5vlJLkg3LnqG4/r00630ZI5/jHMjaGIDzAxXUew7bHFPrOn4IKCgYI5S3dsFizUgJzCvdvt+KBBrHLF+/ewTrLmHcenJYt/jklYxxkCAMmZvigvMFvKM6Bu2cWvRUEjypJHmoWbAJ/x6za11kMBPKen2IgJDPA3aLZ5EBY/6QoIzll9iV2z19IqdJHXFYGyEKHn4RMVSFFYv7JLJSzay5ox75WiAxMCtjcGDgygC+pvreqX9gqYDNNxhnqOIGzcm0XtDxDQoB0wdE2HNudhUqKvVSIVUTKgsuCOb0r9YsumQ6oQJtj8i1AhdsS0PoRi4z1TH7J9T9oDtu95T35hidiE2sngf2kBXAf1XqIDCURzTIK0QjnegSb1QB71y8GEfofQ7Wkf8pZLfKZddWbdC2RmBkkcD1eQGsPZZ3RYNa8YJdqiRxtg4KxjXgMxvwZ/ePUzo76A6cE8GT81tC0JL+8BxApwMTN2D2+jrJFVl3+vEgRpswPcSPF7d0s/he1eSGQMG6afMS+ju2kZx4vijjy0Ta5/i09r4gKp4TzwSoD7zvnH9N9xCH8BDIERf8sFrn2n8e6juni0pvLhW7t9dpjBRHqUoANHUy1OB6yofUaVEqHTqVHfGcfzB5pK6hpJOy+JTkVVmcW86zyN2sEJ6OOZ16iHktBBATPHsPdIY/b6dryyxrdN4guXGyqgC2QPme0SD4C0eeHncA7fF+OorB1ydqHwws/3QdBQZ3UiVYDna25tDWNP3ug="
          - name: "ldap.ldapUrl"
            value: "AgCCyVHM9MJ4BvRq9JEIE5+/BhHIWaqTvzytKg4rkHzknNEV6P1jFBNuKUY5x27OtMuiAKa0QklBj7TvpmmXFKyIw5hBP8Xom5OBU4oVK/8QOkTs+t79eAJjdlVyrd5v5OmBcfGwZlSv9eL6mcE8R0eGc6zXnNiNoxuSDroYbW8f1zka2MCzbGMy2M2kMcXy2ZxY5MQ2T7qlNa/ENDIsCIsEep37tSzaHIrjLKkb5nF/TG+VycxDBP9i2XMtW1IHMPC7/WbKQtqPAi2iFMqT256NQmpZb7aP6cFjaRZYWW8mfwAzu5uWdscr4RgSebTxeTUoUhWGxj8Vs5KhMGOIdV3HPzxfGFYI0kFCm/EYMAXMNXvbGOHjfiCZYWkWfcw/FVMs/JaU04GDFFx8KNezIh4871qNztfsAm1tcR1x8xt8Und5c7aa3hfLF7rMIyjNl1RP1EqSQtplPyeNpDrzG+8AlfdCRwBHxk6Yb5+IoSXGgXXy7w90j89nHQrKyki+AoxwGrsxy02YiaJUpqfQtJomDauN4wNo87c/S/GWa97jyXbHK1pn2O/SVD1thxVpFBuFoO0Nv1OyN3C/XEC1E63vQc47r+MC0SnAOdG+Wkh2Q3Yy7jXv11XRgI57mRDIXQtZjiI9newsYikpxR2ey0x3KeHEdO9evVu83xhi6FSmm4PVIY9/teGZ1ufitOppKDVHqQW2lzf3hqmAal8eoIl4azjU5ljvBonTVK+Obx5j+AUUCoAwZrBU477wDcLn1ncaQ4Ji4SWbGkVafe117xVFoU8="
          - name: "ldap.usersQuery"
            value: "AgCGUAI/Jg7xX9g81IKrz4+3dXfXYxSwbJ8DQ0QcXD71Dj2RPk7vxbXrLKtVhhWTteKTEGcBdQFk+rlxZYoBtwNrCxPipmR9ibthuSHMcGbMAzIOjp9sl0z2hOXBebDbYRh1BaWXf7lXFvGVk0xFJSdOjaHmDWFJMoCSIYja5NQTUBf46eWi0cgo5XpiDpzV0GkgwGB4z6Azfdu/O8UUmDdoQFRqhj4tQDtHNGz2ZuOJpDnJAltL5Yj/FOVxuWS8PterGY2wyPhoBEAJDjK916IRg6VSFl5IqeIQOOiz9FVN7pE4Xrndy++2xYQnvxlNTWNWkjG5KGnaSWwPqv2/KapAvTErezYWjSiWkb7Xv/hXBKMRgjbgqnco27/5+7vmsai2WbeElwwQyx+Xp/V5vV+cZbLpfZA/4xRp+/4vfF3wOsafD88GSp6Q+3ATGLl6Ter7g/ErCLydXmCQwKw9GCHUclMwcso6yJjLwl/MqJblRT78KbLIN9fwcXWetX9IuWLXXKiVr7VRwEkEdviEjKZIJVOmP79Q1RgJ2KVRGMNj1OEyi60PBrMSktuTWwKJq+619MTJ/r8hleqhRhoE8jRsglmUfSeZhIoqGJEjTHwWdlhy2NM65Ye+i54zrKUSgA/0nUJOvuRoFsglF1JVbIeOvcSMQ+Ok04ZyY7JA2Z3ZVGd2d4tLycRtYjxphgK+b0ZXNa7VCHwRoZebNDasBPQR8EIOYaOYQq68AfU1nZYAROrYwX0="
          - name: "ldap.groupMappings[0]"
            value: "CN=OC Editors,OU=Groups,OU=GEPAPLEXX,DC=gp,DC=local: ldap-editor"
          - name: "ldap.groupMappings[1]"
            value: "CN=OC_Administrators,OU=Groups,OU=GEPAPLEXX,DC=gp,DC=local: ldap-admin"
          - name: "ldap.groupMappings[2]"
            value: "CN=OC_Readonly_Users,OU=Groups,OU=GEPAPLEXX,DC=gp,DC=local: ldap-ro"
    ignoreDifferences:
      - group: core
        name: ldap-group-syncer
        kind: ConfigMap
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ###################### OAUTH GROUP SYNC  ######################
  oauthGroupSync:
    name: oauth-group-sync
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gp-infrastructure
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-oauth-group-sync
      targetRevision: "*"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true


  ####################### CLUSTER-CONFIG ########################
  clusterConfig:
    name: cluster-config
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gp-infrastructure
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-cluster-config
      targetRevision: "*"
      helm:
        parameters:
          - name: "argocd.workflowrepository.username"
            value: "AgAQYQVFrdCMm9n+Fa4RPUf3i42IgwBHKhPtvBVAMxAgo8F4FqoFRZhsaZ3uL8m6SjCDeGfpzO9IkguGXfzLjrxIiocf8lTgiu6vLp014f3C6IZIyZBKwoBE0RdIPQqHd4CXhwRZxJ+ABkYCVl+oD5YidHBJlQXsiE2AvwZk3TDekryf6wFohwKqJHr5AuUUA7RTPwyEOHF8ZkDXqZArz9M6eMJydLOjsbhbn5aSY70BMpB206yvZHkxqTRddmVn/cQ3ypCF0oKWyK2s9ifne6Iv6QSzD/AcMjZz/EIB4/LlG3sUCaNUVfyRRte2WyvGpoAceojQEWbbyeUQEOwepYQ4BNjg0N6A1ctfOX28xiOr9U421glBBWGqRKODDwlev21NxE2suxdXJuohEoPyKFxcqLNuFbuxqryuXAIWiQD06a598dmUUcQamRSUK5UmvbahZBXS3889C697ZQalf3UhWjSlf8i11nVELgVNkXCDDghZFN/cEtYyAsqdBT7P++wRA+fKLHsYfvh2FJOHGx10H43xk5UDtQ8uwfL05lJhg9xsag4cplNiTE52YSoiAoUcT/dWVsVRSvs5q0dHG2xnqEXdfodSCr6D18ly6iiJbtkepRZz/ST5qmJxYcP0ti6hcsV6drK04DolJglZ12Jw0Sal26fkbvfhR6vOjde23L/oFcUkztZ4jlemu0Oi/UWoBSx0v2RQhF6yTR96e4XWGA=="
          - name: "argocd.workflowrepository.sshPrivateKey"
            value: "AgBNvIMgQPX1ql346GTyulruk4ljFlheSnTL6qjPjbgrKNRz3mrlXokLSIVIZlPETtPxSnleu1jfJowwPFBlRpGSSSDwH2E1pt2nnbpE88iGvF1IVds+fzTwXsowR94OcLCWA11rPIUiexA1snvCp5nWcDz8ZxMtyFpcce/NGh1JB5zA6uFTP2tPhlYvtwfKNw2prOWo5fEMR0eWWO45qgIbPssNFPM9bTf00ita2VUMMi7AC495X/4Gld7b+ArYASzrpXkMRMhxnwU7pKCotZ82JuJaL5OPzTHrOQoLiHynjwg7NUi7WWzh2dfXBkI2xi+PeTIcriS3is1TWy58c4wVT08xsy8UPLhqR8IBddG/FXSJjjlJ5Ww8DbWCWHtNEQVZTzOc8gBOW+gz0XNyK+BM8wJnwjvCAnMxxlT8o62FMRwTOrXRKOVzXJd02ByE9k2F1ym3Fbm3FepnBFeOStDFU2TGbFuirJa2LI6OoZqY4op2Kfd8i58z2GdrTvR1/QBH4e1VD1NariUckvwBXa2SxVxLK/uqQVvR8tDJUikM7TU7O85mNR6fTEt4E1M2+77o9ud8BLcCeBc+XAXEZwQl342GdclLfNjgMXiQVGE1isPNbQmwQZp8tDWBtYpWO1EiJ5KVP8lDzVW+y1Vsd7rFBhws5hHt54iBHItTa1fcwy8HqjJ/PwK80RkYCz7JCuSs2Zw2lsPAg7RuSNpRa0Dd0LmkgXSvcFn2QJ+7It46FNjwrmEm7Uh8rGaGQ1SJUUipW0JIPnUZE57Qt2ASe4qbVwmaSaS/ka4FNzfNLu9Eu4TRVPYFaqddKneVP4zQkZLllhB6sdTjKPDv3u1b/H/OY1EfbnFod9x/0C4NzxPtnlY/NGonQ7M76UezCv8BDnCUpCZu4CwoRZ6J2Prq7kEYGLyX+rFU2OI+LxNV47K5rMnFTB4TYEHl5y3YBMHRdIt9T5IiqMWGWLzEG6SQNjiRR1KGo4iWC6GwvZ5EU+AD6++MTdwltjHi7OavRN89XOYu9xEiqgOQ7S1W+ERpKlWvt37+u1Jnb/awbE63RUL30qmo8AeyvHcmcYYplKFCTnQhuyhy8w6BwPsIY/5v0XoTrbLhzEYDgbUfq4Gh3rkCSS8irBECPZA3il5aeWaeg/hku0GJy/YGLQlcKEq7PnoI0REokCRp/JvUP66jzkfjlBiVrvuIb1UG2Us0gBubV0JNur2w+7Su+lJAyyrZ0+6IdCO8j83VazW94TioxBnTbRmg55h3e9lYqgSHP+LgW/6I8d0RSWrQctaOiFndQobfZ39dXzwYWATvbADNZRawFTbCxIAO14dKqlKRcL+gVt+SXDvWKr2P9Pd1BlyOiU0RyaIMWVKJ/GTxaYTxc6/2fPmhsTojhj9UabnXVA+dxuz2FxQHZZBCMJ++YtXbfx5VNW59IdRpfh5Pj0ug232E5Mw1fPj623jkTfkmCEIB+sxHbz4OPebkfSx8GaU1I9CzAxbHHOmh3Ph2JHjV2tYR4P2GXzJCnYqgpBWfdJAt6ETxD4F2N69rFO71ckWtTq9eNtQnsk07jpebfK+RxWrC3e6l96VEOo+/VsFvhBOpcePaYEg9c65XOuMxtXCKPluq+EGI7VZN3qaKadqlrVnxsXWWNX9CUITY1WRvobbszT/mQQOWyA+blOeU4ApHgiXmfUqe1GFB53lexQkOrp6UCTey5bY="
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ########################## ROOK/CEPH OPERATOR ##########################
  rookCephOperator:
    name: rook-ceph-operator
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: rook-ceph
      create: false
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-rook-ceph-operator
      targetRevision: "*"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ##################### IMAGE REGISTRY CACHE ######################
  internalRegistryMirror:
    name: openshift-registry-mirror
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gp-infrastructure
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-pull-through-cache
      targetRevision: "*"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ##################### CERT-MANAGER ######################
  certManager:
    name: cert-manager
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: cert-manager
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-cert-manager
      targetRevision: "*"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ##################### CERTIFICATES-PATCHES ######################
  certificatesPatches:
    name: certificate-patches
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gp-infrastructure
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-certificates-patches
      targetRevision: "*"
      helm:
        parameters:
          - name: "apiserver.customApiUrl"
            value: "api.play.gepaplexx.com"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ##################### CLUSTER-ISSUER ######################
  clusterIssuer:
    name: cluster-issuer
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: cert-manager
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-cluster-issuer
      targetRevision: "*"
      helm:
        parameters:
          - name: "solvers.dnsZones[0]"
            value: "play.gepaplexx.com"
          - name: "solvers.accessKeyId"
            value: "AKIATM2YI3GT32L3MCWJ"
          - name: "solvers.secretName"
            value: "play-route53-credentials-secret"
          - name: "solvers.secretAccessKey"
            value: "AgC0OKJ+SdWpMBkeYIqiJlI/73eayOLWxGKefEncyxLSD3aL1BvuW+h9yD4tmsQogonxWcWC1Eh4ifNz1VGw4j3BJOa2frNnxnUDPgEq6gysqG2tinl/wtbfwEAxNbiQHcukX4/r/hdvRK/Gx2M/gPrW2GyM+4oFV31hnlDG8KyZqRszhAtYnrjE0j8ptzSVIfH85KBbeN/lIX8i+ECuPpEOApfaWvuHNfkCoILR+sGHmtgsRNJcPcu57zGXErUfoMvb7VSs2Mqwt02H1rn7x8L6v+E0dcpc5X2N3V6ToaSQcCgYNB31B3cJJsNzQ7funPc373AFlVoaEHH9UAiXSqWifcFzhQ03+nEzVlQkBSOEBJsj2NcFuLZmzg4k7DTBM2A772J/qx8a3bBtfJlATHunIAhnoB+c8EXMghQCeZ9S1eKyBNOwB8yfrhnuWrbKyzrT9pykneaKM19vXZUXWjfSW/Yk0OW5NkXO2JO47x9hWUgC5gy+M2+hNHJ2mpdFxgEi4wO+NBtSYpKQQJTY2clqE6m+fkcvZJ/NsYbsEmgEGhsm1kKg+bkz2T7MB6ZejjMlqMGgmgx8fw2kaQQhJbaecYsVOrOvrjhs//V/lctKBy6C5ZMZ5oouglzzZZ4DCpSGnwi6sKcBEDwhVFA1BSs+m/B4S0bQr/LrxeoPSh5M00bf5kfLwPtlF15WJDeAs94QJBvc7NLJG9mvR285HzqkdJ0UcJiJ9kAt5FJocaMlHvhwMZs3w1nD"
          - name: "certificates.defaultIngress"
            value: "*.apps.play.gepaplexx.com"
          - name: "certificates.console"
            value: "console.apps.play.gepaplexx.com"
          - name: "certificates.api"
            value: "api.play.gepaplexx.com"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ##################### CONSOLE-PATCHES ######################
  consolePatches:
    name: console-patches
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gp-infrastructure
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-console-patches
      targetRevision: "*"
      helm:
        parameters:
          - name: "route.nameOverride"
            value: "true"
          - name: "route.hostname"
            value: "apps.play.gepaplexx.com"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
  ##################### KEYCLOAK-OPERATOR ######################
  keycloak-operator:
    name: keycloak-operator
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gp-sso
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-keycloak-operator
      targetRevision: "*"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true