project:
  create: true
  name: gepaplexx

applications:
################## RESOURCE LOCKER OPERATOR ###################
  resourceLocker:
    name: resource-locker-operator
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gp-infrastructure
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-chart-development/"
      chart: gp-resource-locker
      targetRevision: "*"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

################## SEALED SECRETS OPERATOR ####################
  sealedSecretsOperator:
    name: sealed-secrets-operator
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gp-infrastructure
      create: false
    source:
      chart: sealed-secrets
      repoURL: https://bitnami-labs.github.io/sealed-secrets
      targetRevision: 2.*
      helm:
        parameters:
          - name: containerSecurityContext.enabled
            value: 'false'
          - name: podSecurityContext.enabled
            value: 'false'
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

###################### IDENTITY PROVIDER ######################
  identityProvider:
    name: identity-provider
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gp-infrastructure
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-chart-development/"
      chart: gp-identity-provider
      targetRevision: "*"
      helm:
        parameters:
          - name: "google.clientSecret"
            value: "AgBR6/2xnoPliY7FBmP4dC+9QvL8p1VjbHWq74q2Xjr0sZvtmYJchEfJ9PiuT5nyrK9VsBpHtbxbY24xRIoyjT6j6bgnI9epwgH/UKdrXETVfyMHxGjIzsk6eqJalKJKKdNqK+YrT6tjwo5pl9dxWQu0JRn7BOw+ovrOMVOY3yVG3sMK6TyPLzimlqeEiBWSBvwy67eOTy7iuo+jRrsKmgnrXoa2c1EdgIF3Uq1QT7rz2peoEoiQ9g5pEEJaf9eYcYcU+SZbxMGU7XlY+ma1e+d4iRJV7TJboWPH0s2cIhx6kP3sCAeX+iB1mD/D5EfzlB1C+Vv+ixfIUMjY7MB2DOgfmw3bZM0CV9Ke1eEXfnkwQJ9TU1tP859uer22bO06fC+F7PyFAQEvwM349mr11pZn/SJTkyrCtZDSwmxA0HQGPqWtWd9qaMrPsFhU4M8fHW/sV88KwMj4e3vx59Ni05oeaoEOjJ+yzf1k/OpMVK6M7REqVK2FiABrCCi5xlbx/JhrNMG28AmZXsHryb0Y7dbSxXhB2LSg4KRpt8pmrpeXe16IfQO6WReveg4pCDdG2VdETw7mHfaGlPgFNyuV20Wf8ozq2gW51PDKCOBg61w3Il0yAvQcSxbr9EE9zHkACRntqSlbx8dMVu4OuD1x1VapyRlUk3/obYxfTeDqgVzE2wKHVMTPytcaLQyydsgCTST+/PwhBqaYzNjNzVz3IBPJxJjbziylG0X0"
          - name: "google.clientId"
            value: "AgBjuExlJRHwWEWz37RUta/yGaq47D529+NNkjq8MtjvDRUy/tGE2Rdw5G9HvL2CxkHCYO+UYW6kM00JOkEzoG7VdDHwocgu2tmhqxvpsmRdg109KyD5BWGmn68qAKE9YdY92IpR7EsC541bAbEfLzVuyLV7ckdvHUS5BdVo1VLXXTt8kE8zDSWR+H0U4Pp8NpPY/FQzLt0YdEtYMlr13sfj1wL2Lf6p7Q/F76sdl6zFFqrheMLGM3IKgqhzvF0dH1oFQHry5CBOgiRI6ydFsJtdsfzzpkBMI2cTET+wdthIFlQseQm9RtJm44TpBwjTDrV/NecWm4R66wLujeraDpT9AhvdWcGsO0ahKvHlWn7ebdbUk9NDi62Q/T4OrKLXJ12ALsyJHPCedEQO5tISUasrYRXLKqMbY1FGyMpscPOOvLqI0gw9QpFN+k3Xahb9WS1LCCt0OP0bel11XVl0US+oH+nmltdL7cEvFUlzikqqSi5FJ3cMJ2IgAlmspyNVR3/CHsDUtJQ43CgWnYE3LczD3zzNcO29QRoOciVdphzdLPKtOrxkv6/TsASZzTf9zH5mGSj1GXAu+cf2W2j7LeVUZGCxf+kZTf5Ccy6CNw/uMz19uUJXas+DTo9XK/3RkTG3JaehyfIgH12SnnfGF7G95CZyDx5yorCfW29q4qssu9Fq15nXoP4h1sa7DbAO1M5jnwAC2+1orTgQAC13bX1pNakJo+TwYMqUKUrE0AnK38Qu6mZmE1WQiT4pHh4QMK6/zup/67oHL5i5IAOceM/FQpDZqEb5pgD5"
          - name: "google.restrDomain"
            value: "AgBTP8zGqpaJTA8PMYtlHYIbQ/0BrgsKpeyoTJWWZFvByrzV1PnpXIEyw/frU6N4+A8DXAkLC4CmiXgRhAsKblNPCCFape4pTQLM95WhxDsXXaTKim3Bl5HTyoEZ3J3WZ++61XksvR0qARkK4KNpIDlKeyBn4nmQPgJz7HgMWXMHnTryGhHqhXUCVPf9MgdrCZDDngbOQW5HO4dKJKxMH0QOjV8YgiyQ6aSNMWgxdYS+Wii1EbASE+flg3nAGpJTrLcNr4P8NZpbs0H/OPS0VXvbh9cDP/RcatSZ3jg3kDptrAnWw7WswA/G7apPrFcCrc08LvQglvLeyBMuEsZ5DVStX2uZBKsJm1qbbwVfrw7Je+3GcTHx2l/zoFULj8Za9IeewmbAngeJVVLQ9cWm0PS7lNkNF2112fq/x0bdxoZwe7izilFj3mnHkA0Zr7Ztx1D7WFm4cXNfnlMmrSHXOX2dGLwWRjdiAg0Ziz6DoSgezTyJrWsRxNnSJzW6L5jYA4x7zJAu0f2ofL/AkvrY5U98IKrSpcwWk3tPZEcUCSM0NSBsH/Iu1SZQUKQWwd8lEZqAeqSPdvUyQOVHbGjmZDDLk6sYul4LkgL9XNjKYcsIvEZjXwuaeeu2KSCRR8gxP7AVi3wVMzIWm8nqSWxQQtsrodynqVlfxl8HBkMmlYiquYXhn1mo9stha/gAcGXNRK/wk6ZdFU1Dy56DKgns"
          - name: "google.enable"
            value: "true"
          - name: "git.clientSecret"
            value: "AgAUbFTUudYvzAStHgXXygwbu08sR4FeOW3vnBJ6rHLJ2QtaJ3iWoPEnGAICcBhWn8cc3pU7JA0G0PQORmldNH/inkqj3bEZVush3WWoE/NDKqlMujj9KmOzQ13Xd4ISDIFJ6u1cjYoZQU0oKYA5PIas94q5E5Zcssj+MkpsIAg3BpPxgH0+5HU+wGtWVRqG8wvBJ6HybCBQLrl+wdgIHjTuaXCfPnB5AKXRmD4twZ0A2hduO6dJ8hMx6Y8cI0QclRrtIfL7q2Ip3TvDY7C+FcObfmYZ6MdPhlMMgNkDlcPMLdj+D80HYdx3QHZgTnTbZRNQVvupzCx0GGeLhTK4ZQdxhN768KmEqF01KRu9Mhh3hkXjWp9I3oPprMkzlJrYtY04JqjwCAdh8hbozolKmJEgkWXJkm1MdZr0X4+wZDOzz017nQyWSAjrUqMqE5G25tiZeHcLAaO//7GLSq5iQATYp9ty3/VFceWbjtHVpFr9EuQ0GQtYZZateqG6xEJ6L5K1WO5hTgrFrGkZDagmt9q9C2BTHzXrQPQhGtKbS/JF+t5y+1vNHzJTFIYWL50j66ARMlyFVGQ/HMOGCyuPdJu9MHXwKtPd5XI/Xgi423G/ILPXYwLtGjmyv/MDcrRBQr/1qwEfka3U1k6FjK9hWOHsVY2YdUNV0dSKIzPgBYal6vJWJ3beon8iX8/iOaQF+CLAJntlxx3QCrarONcSxCYiPCKOwHLXoaPGqaxUmbda2fw1rZAoiosJdg=="
          - name: "git.clientId"
            value: "AgBnclhFXitvpVoNcNhsM/4AI+lT9lfPBZQ/xRNutGZ+Kxuz//o7w90WJcTT4UMEVMrJAlodPPCcz1YG1fApA0KmAHYa7e2mUpplSPCnD2iQ6laArtnNUy2841Jb0dROx5LutwDFDJtq/VNxuHQS4I2OtGjZlHrled3bjkxA42OVLlxfz0LgTYm+hSgmbyMUYDn9B6J/3xOt19Tz5eR4dyhS9qY0P/AWggLnZIvoTa5Ri5s8d879MV672UBBefQgYpR5m0kQtRmJAccLqQ40OyFV84NsVzt3E45OyJOvjCWVmk2p++wp/HWnu3Yeq+2gaP+FyjTIdb+oCf6VPENe+5IuDK3LbvAMkreX5+wIVUjXTSzbWEdGRLe/dA+S+2w8NqFup/vGYv4WOEBUQyih13uX/+4Np8LxYTVeX/gSDvRcBXNfanOMOz5kw0W3tevnKoBGZObLbKKQlBckO3SOZlX6lnGsgMvdlf4i5O38/wee4/zFC5VOUACeovfn/edZANpz8hiCmpHTvGPHi1nVRPlikcruHMK34/uZSy8OooHO/4/natlbXJopTUNA1Wo2YFMvKZ0lVgOB86ByU95qay7NVfViDM/n29jcc3c6sGfaIc+3Vt4iBUtrimh1fLV2TEngJL9TQhAGAjWq8Yk7Z47Bj4yxNzZHU6EslTCC7Ji1AZJnYVQn3+yHc4c2Ag0eM+ZoFw+O4U5qPzhiiCxLrwSVPkw/w+g="
          - name: "git.restrOrgs"
            value: "AgALBLY5jJeWPHJAZs+/OcOwXlBHJYoWmFk9WNz19+LFlQv7GICyXHvnwGg53KvBGc0/7irzE3JVfMuc0ab6UkglqiyToATwP+aWfW6Sjq49Van2Lrh1rC78tD0oz/3ZzSNaids6wgzM9lnbfDCI0Pq0OkfcEzGOK3d/hOC22nyqUsqs+MgnTKKZhmFaQPLhSNVN5ZUlN2fGips9m3tqln3BjHLKYXEY2ocz7q8rPNnMu3eRf/n9B36IG3PkUgssRAw9q5ShfD40sb4rsuh5x7QPL35/32GCEJBX5AtfdT4oDZ7sKSb2PHlAfc8+SM3rsw2p0FaY8va2RnOt4B/z+sd7qwD8RfJkjbCdyakPhk35Z+iDWc7nYR4OpQkO0YN18ags9hTBKO9hSS461TxAMhx/u5EWsL/xIJDbs4I9XzyScPLW9XELzFycfnUou7PxlgVjZ4aiZ7n5uogm31E4+YK8uFxkPjJanIwqutkCfPNs3ajwSSrKy9i5amh4piLHfTlmmNGHQiAbEQRM++cF/pWjoiyT+5lv1cVpxe6I4A3V4/b5r7Axyi/95JCNBZXTRNCqWXBUrKxEFU+G5PJ2ohvsgtkwICZBJkb5gd9it++vOApUDW+O3E/lomRhGjgSbsh9Gc4GyYPxaRSzXDCUz/OO81Wx+1UrHoalDiPmeFcZgksx1kJMQOnDpGDlbY6aF2+ZgSaM1wq5G7trEOMDxj2NmBQVccY="
          - name: "git.enable"
            value: "true"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

###################### OAUTH GROUP SYNC  ######################
  oauthGroupSync:
    name: oauth-group-sync
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gp-infrastructure
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-chart-development/"
      chart: gp-oauth-group-sync
      targetRevision: "*"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true


####################### CLUSTER-CONFIG ########################
  clusterConfig:
    name: cluster-config
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gp-infrastructure
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-chart-development/"
      chart: gp-cluster-config
      targetRevision: "*"
      helm:
        parameters:
        - name: "alertmanager.config"
          value: "AgARCl+MTf0TBxvYrwEMPF336NJMysmHOcsZNyP++j2FbkYzEIzsIEyYghGQlMp9vruT4qi2Rlt+ygZtN9nnrkH35s3sI+RlsOuGZfzr6rwTSw/7LsB/HV1Zs1DmKskGnWobLAL2N4WTlbqAg+Om19EE34GShodhaKIjnvi9ZB3sOLvey3ch1bNOFpTU9DGGIcc/dWe3hnGK6yV/LJ139jETT1WjpfAbVbJPDpWQCdQHo2hUggQY8sOrM+6On/bK9iRJ/MygXNnBo2cdDGG+5al+3bXs71knqP8Awb+0EM2fbzpy0fsG2GN+CSnPUQpC9eMV5qEzbYt/GNlPl+oNbATD7eVcZCXSzPpwt9UlBtPxxuKfviaWZotVN5fYtfd3/VXI5BS2zdJmPlxfLnIFX6Ti91IleOpoAbAqayFlSafLFGoIQS/c4awcLugAs4Xg1emW16NcRPR6dELmY80HkLyPSG9V0PTUtkKhJrq/C+6SdTsJ4Xs4GKQsAGYLvdC9sFVicm7UAD4r54GgWZHFVG1T5qh7XXVz2CwGqlx2VzQ79SYyGhV6CiWRLXBzc21SyVGPRXm4w+5n4yzCFTuHipoTXoTkzjYHU3Yyf86fGArw98bVxYn84s1nnBX+RS/227d7xmv8jypxcEB+qCkGLD1lJ+oYAl1+dUP91hIBkok+UMAfsFZULEP8PPBvkKFb4fyU64EWc2itqdjMrOHEzvwDu2H/wMSz6ocLGRp1L6J/ZB72vRJci3hvNYxH8tIs7JB40Jm+8GfVYTcHYBZ3VXAbumzKHlA+i808Pf2fO3bzAIrlcXubhYR/ya6Vt0dbY8Bd4nOdYeZ+u4NDKDxx8qS7MnyxsysELJUXDgL4fH6A3L+bBLY03laCyzlSww3Vs6CXgcE0CA0QjMfTuBOSc1fXqjgmXW2i+yOUh4pqlIVP6iFZor1frZOl2Y0wTkdZwGziVhONZFxS5lqmggApaoVbHYwN9XGvqHJOBBrvPGhH1NhRqcv+/Vl7fwNgoWpoGkDPoCQajA9i9MjXB9RqQTqG83w73eyHTicANEoKApm7+/3nWlz65BxmdJe0//qZu8wSWh4PAYMQ9HBXBmzM+Y1gjLCX6pXDmP0+Ql5fO5GikXDjVv9VxFBwHpLctc2806ZOZzqiOH/hUjK0kzDXtb+ZhSz/xvLPISlunfow7Jbs67W3UWhnggQtOU3G9MDsYQ3XwE05+Tne095Pb0UvJWtmVEiIKiQqQQTsZ2uxbMC2i+ojkn8nuqkl6CPv/XfWqWlnCaK2a9tHFaKC+eG29eBir7CbUj8el8M+lp8mxwLr7gvblIfBI7moaltAL/+1LcP42lV6VBx4dj8QmXCuDoKBYPt2TyfWRq5wmGiOjyYrM3F0t7XPexXasWeVRshmd2QTbqQCDkSlmT1q1V8/6YWTRk44iC7clK/exqPL5RdDrh6r297mVeTu9787rnfWlgrGur+clr66JRo9gEC3+smTl3VtOBNX3l5gphXT63rQP0RkqHUC0M1yIIcW4npP7w5/hZDOoVP3RmzKkCqg5z/kK5H+JopJr6Jh9yGlqXXvbMfPF7r9S8rVX6SNVwC0raVWIDUhaLUI6DyRaMenb9EbT60b1MKJveqapAxkEcCJsA48Nmvg5l5QZv+QY+mZpBNhNq/Z3Q9rQuJrEKsCWsGXnxqNr1yQUq9tsOpVK8WtT8h3fKEinI3LE4kKlausp1mkrTPkKe1nne9lyO9WBXuupWSMkK7M0ZEYQOWL3/vGyDBMaCWQd/72q/U1+u0ESoAg8qx2CV26b+y8S5aqU8pEMCoGk10UmS87mw3EA5HLq3/r69hQaqEyUpiQIUKNkzUPH9953vTpFPfhoUksCbbgu9pxTGM7rH4cei4cBfr20p3kavR/4J8fPZ+Csge3yuGWx4Ner3LJasTE2I2Di3mWCmzqFQET+NyRC8UBRoysXzlOek6o4Uxp3XE87Wpd/kWBDhakur5u7uCDEYMYvRu0O44tBofFQygzX2NXwUaNp0az9qXI0wBtjpF8EQ0t/sJHfkwJesecxnZF06xa0shcqwx8XlOmfelHg5sQ5qkFN1rasFiwQgazzpnBL0dBKkNozB/V4x5mfb08XypjIcHyed/3DxQkg9hwXJ4pvzMtpziLn9aBWZU9gWLHv2twN9lFZldpdXpcvtWs9PKRFXGpZaCziq2tl4pKDy8OEmNJ9E0bmn9t1GdiwjMsLpd+sctc+RmW2clQqVHwu1cDIiUXQWETrtYtFjiClKooMCvT/L1jY3L19ZoIttBAoWhrbO17p1FB+9UWuOOZZAloCCt3pVD76SIuS+uflXk4aZcIRG4b4ohj8l5+W3WPdPBU5p7fhhFAtS0aNxl1NmqQHBq/xzPtf5RWFuu8+kBknpSCF81TaRxZKCMR0ZNU+JTZV4W82jZHW+O6KDDR2KFlauPrPI8iLxsDWnHiskfE29pcU7+tMe8gFsRsMxhimtpVGB4NilkJ3fBRYYYjoXrUcbDYKTMGElef2LTs+/8zoyFAHTtUPe1Sle3hi/AnsLvteck6PBY8dF9GDngs178134hYbbSKgI9Vq/wj4/m17c7Lw3ABsrFAMMRnE/Id/CB+k1gOIKOFfxJXvGyLxn6H563tiiRa1kMJK/dqfeLtdDBA0dzY88RZUihGmDz0VlO7IJ0Rssb+tEfWZ6zpOF7oPQiPJuTsREkSOiSlfd0PckR8yUaR74htJNKN3CAF1kaN3MfQ+TvWdZgQOcTMHOsB7D0YJYrHkh5tlUSYWHB8Eg=="
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

########################## ROOK/CEPH OPERATOR ##########################
  rookCephOperator:
    name: rook-ceph-operator
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: rook-ceph
      create: false
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-chart-development/"
      chart: gp-rook-ceph-operator
      targetRevision: "*"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

##################### IMAGE REGISTRY CACHE ######################
  internalRegistryMirror:
    name: openshift-registry-mirror
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gp-infrastructure
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-chart-development/"
      chart: gp-pull-through-cache
      targetRevision: "*"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

##################### CERTIFICATES-PATCHES ######################
  certificatesPatches:
    name: certificate-patches
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gp-infrastructure
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-chart-development/"
      chart: gp-certificates-patches
      targetRevision: "*"
      helm:
        parameters:
          - name: "apiserver.customApiUrl"
            value: "api.play.gepaplexx.com"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

##################### CLUSTER-ISSUER ######################
  clusterIssuer:
    name: cluster-issuer
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: cert-manager
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-chart-development/"
      chart: gp-cluster-issuer
      targetRevision: "*"
      helm:
        parameters:
          - name: "solvers.dnsZones[0]"
            value: "play.gepaplexx.com"
          - name: "solvers.accessKeyId"
            value: "AKIATM2YI3GT5EKYOYDT"
          - name: "solvers.secretName"
            value: "play-route53-credentials-secret"
          - name: "solvers.secretAccessKey"
            value: "AgCAQlM7Yle8rHcKKq5t8MC5s/kJfV4GoDvKY/rHXVjSiO0emYGO+lF4xsfQsRhrmiCqyEKlRY6hSzl2Q1PmJuE5jZVz3sQIdeca/Q61YLEmN6SdWBWu+UYYc7rCm9unXD6pPX4JrRQ2YBP2J157OmUXQfl7tKk8C03w5RTR9XLxLA6uP0hnE2IBkpMeSWecj7kky5heP8COojJQBmXS5H1ZEGCBChIKJXl2dCYzbRUA9+9pehnelxuO1n5SJxjlxRUm0+N+LdIPdunnBW/3o39qGAthlIzYqALz3u/GiHKx/aai4pBN2D1ap4IzNlf0Yg1HgdxmvOBv9KK+7m7ag0Lk5BVssicsf6Cv/1v8yfAmKOeNNA4t0suUcZGHH2RmQo0e7YZOktqKt1iHkb+sMXhhpjWGY+Q34h6vjh1nstyHqf3cB/l+plUCOZmsPDpi7kr57+z4WuOe6V1XqQ1Squ13xN/973m7EywBTOUgI39JrYt02mkufHCAeBmF4zSzDK+J/ihh6rZBhKsMPQ53dOfT10wLsV+Eu/xal8ZfyitIdisoUruAeunMcl+i7e+sOXrBzxY+nptz+9H0zE9v9tqNRa+tnc00Sb9GsXlH+ky4t1A5DFF/EyC+uE7B670O6E1y3KqSLRbyDIbbf7i0qQEbfRxswLBFPguz+cvDvBGQAC0KTXDK+XKT9deUiagymVnTTGM1QzE/lvXotTzGtBLgNMtZ0ZZTOv/Y3CNxKUA="
          - name: "certificates.defaultIngress"
            value: "*.apps.play.gepaplexx.com"
          - name: "certificates.console"
            value: "console.apps.play.gepaplexx.com"
          - name: "certificates.api"
            value: "api.play.gepaplexx.com"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

##################### CONSOLE-PATCHES ######################
  consolePatches:
    name: console-patches
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gp-infrastructure
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-chart-development/"
      chart: gp-console-patches
      targetRevision: "*"
      helm:
        parameters:
          - name: "route.nameOverride"
            value: "true"
          - name: "route.hostname"
            value: "console.apps.play.gepaplexx.com"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true